<?php

declare(strict_types=1);

return [
    /*
    |--------------------------------------------------------------------------
    | Output file
    |--------------------------------------------------------------------------
    | Where the generated TypeScript schema file is written.
    */
    'output' => base_path('../packages/shared-types/schemas.ts'),

    /*
    |--------------------------------------------------------------------------
    | Scan paths
    |--------------------------------------------------------------------------
    | Directories scanned for classes annotated with #[ZodSchema].
    */
    'scan' => [
        app_path(),
    ],

    /*
    |--------------------------------------------------------------------------
    | Locale
    |--------------------------------------------------------------------------
    | Locale used when resolving Laravel validation message defaults.
    | Falls back to the application locale at generate time, then 'en'.
    */
    'locale' => null,

    /*
    |--------------------------------------------------------------------------
    | Server-only rules
    |--------------------------------------------------------------------------
    | These rules can't run client-side (DB or session lookups). Behaviour:
    |   - 'comment'  → skip with a /* server-only: rulename *​/ comment in the schema
    |   - 'fail'     → abort schema generation with an error
    */
    'server_only_behaviour' => 'comment',
    'server_only_rules' => [
        'exists',
        'unique',
        'current_password',
    ],

    /*
    |--------------------------------------------------------------------------
    | Custom Rule objects
    |--------------------------------------------------------------------------
    | When a rule entry is an instance implementing
    | LaravelZod\Contracts\HasZodSchema, the generator calls toZod()
    | and inlines its return value. Rules without that contract are skipped
    | with a warning (or an error if 'strict' is true).
    */
    'custom_rules_strict' => false,

    /*
    |--------------------------------------------------------------------------
    | Schema name suffix
    |--------------------------------------------------------------------------
    | Each generated schema is exported as `<ClassName><Suffix>`.
    */
    'suffix' => 'Schema',

    /*
    |--------------------------------------------------------------------------
    | Header
    |--------------------------------------------------------------------------
    | Lines prepended to the generated file.
    */
    'header' => [
        '// AUTO-GENERATED by dragosstoenica/laravel-zod. Do not edit by hand.',
        '// Run `php artisan zod:generate` to refresh.',
    ],
];
